import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const orbit = await readFile(new URL("../app/archive/orbit.js", import.meta.url), "utf8");
const replay = await readFile(new URL("../app/archive/orbit-replay-button.js", import.meta.url), "utf8");
const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
assert.match(orbit, /className="orbit-segment"/);
assert.match(orbit, /const ORBIT_POINT_STEP_MS = 1200/);
assert.match(orbit, /className="orbit-point"/);
assert.match(orbit, /i \* ORBIT_POINT_STEP_MS \+ 240/);
assert.match(orbit, /<OrbitReplayButton \/>/);
assert.match(replay, /element\.getAnimations\(\)/);
assert.match(replay, /animation\.cancel\(\)[\s\S]*animation\.play\(\)/);
assert.match(replay, /1월부터 다시 재생/);
assert.match(css, /@keyframes orbit-draw/);
assert.match(css, /@keyframes orbit-point-reveal/);
assert.match(css, /orbit-draw 0\.86s/);
assert.match(css, /orbit-point-reveal 0\.56s/);
assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.orbit-point[\s\S]*?animation: none/);
assert.match(css, /\.orbit-point \{[\s\S]*?opacity: 1;[\s\S]*?transform: none/);
console.log("✓ 느린 월별 애니메이션·처음부터 다시 재생·모션 감소 정지 상태");
